name: smalltextpad
base: core22
version: '1.5.0'
summary: SmallTextPad - Simple Java Text Editor with Encryption
description: |
  SmallTextPad is a lightweight Java text editor with optional file encryption 
  and multi-language support. Features include basic editing, undo/redo, 
  printing, and encrypted file format (.sstp).

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  smalltextpad:
    command: bin/smalltextpad
    desktop: usr/share/applications/smalltextpad.desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - opengl
      - removable-media

parts:
  smalltextpad:
    plugin: dump
    source: .
    build-packages:
      - openjdk-21-jdk
    stage-packages:
      - openjdk-21-jre
    override-build: |
      # Compile the Java application
      javac -d bin -Xlint:deprecation @sources.txt
      
      # Create wrapper script
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cat > $SNAPCRAFT_PART_INSTALL/bin/smalltextpad << 'EOF'
      #!/bin/bash
      export JAVA_HOME=$SNAP/usr/lib/jvm/java-21-openjdk-amd64
      export DISPLAY=${DISPLAY:-:0}
      exec $JAVA_HOME/bin/java -cp $SNAP/bin wagemaker.co.uk.main.Launcher "$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/smalltextpad
      
      # Copy compiled classes and resources
      cp -r bin/* $SNAPCRAFT_PART_INSTALL/bin/
      cp -r res $SNAPCRAFT_PART_INSTALL/
      cp -r dic $SNAPCRAFT_PART_INSTALL/
      
      # Install desktop file
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp snap/gui/smalltextpad.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      
      # Install icon
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      cp res/smalltextpad_128x128.png $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps/smalltextpad.png