title: SmallTextPad
description: A lightweight Java text editor with encryption and multi-language support
theme: jekyll-theme-cayman
show_downloads: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO
author: Ricardo Wagemaker
url: https://gcclinux.github.io/smalltextpad/

github:
  repository_url: https://github.com/gcclinux/smalltextpad
