name: smalltextpad
base: core22
version: '1.5.1'
title: SmallTextPad
summary: SmallTextPad - Simple Java Text Editor with Encryption
description: |
  SmallTextPad is a lightweight Java text editor with optional file encryption 
  and multi-language support. Features include basic editing, undo/redo, 
  printing, and encrypted file format (.sstp).

website: https://gcclinux.github.io/smalltextpad/
source-code: https://github.com/gcclinux/smalltextpad
issues: https://github.com/gcclinux/smalltextpad/issues
contact: https://github.com/gcclinux/smalltextpad/discussions
license: MIT
donation: https://buymeacoffee.com/gcclinux

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  smalltextpad:
    command: bin/smalltextpad
    desktop: usr/share/applications/smalltextpad.desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - opengl
      - removable-media

parts:
  smalltextpad:
    plugin: dump
    source: .
    build-packages: []
    stage-packages:
      - openjdk-21-jre
    build-attributes:
      - no-patchelf
    override-prime: |
      craftctl default
      # Remove problematic external symlinks that snap store doesn't allow
      rm -f usr/lib/jvm/java-21-openjdk-amd64/lib/security/cacerts || true
    override-build: |
      # Create wrapper script
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cat > $SNAPCRAFT_PART_INSTALL/bin/smalltextpad << 'EOF'
      #!/bin/bash
      export JAVA_HOME=$(find $SNAP/usr/lib/jvm -name "java-*-openjdk-*" -type d | head -1)
      export DISPLAY=${DISPLAY:-:0}
      
      # Use SNAP_USER_COMMON as the home directory for Java
      # This makes the app store its config in ~/snap/smalltextpad/common/.config/
      mkdir -p "$SNAP_USER_COMMON/.config"
      
      cd $SNAP
      exec $JAVA_HOME/bin/java -Duser.home="$SNAP_USER_COMMON" -jar $SNAP/SmallTextPad.jar "$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/smalltextpad
      
      # Copy pre-compiled JAR and resources
      cp classes/artifacts/SmallTextPad.jar $SNAPCRAFT_PART_INSTALL/
      cp -r res $SNAPCRAFT_PART_INSTALL/
      cp -r dic $SNAPCRAFT_PART_INSTALL/
      
      # Install desktop file
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp snap/gui/smalltextpad.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      
      # Install icon
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      cp res/smalltextpad_128x128.png $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps/smalltextpad.png
