name: Build Snap Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-package
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Release snap
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.snapcraft.outputs.snap }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
